FROM node:16.13.1-alpine3.14
RUN apk add --no-cache git
RUN apk add --no-cache zsh
WORKDIR /home/node/todo-frontend
USER node
RUN sh -c "$(wget https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh -O -)"
ENV SHELL=/bin/zsh
ADD . .
